<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Authentication Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used during authentication for various
    | messages that we need to display to the user. You are free to modify
    | these language lines according to your application's requirements.
    |
    */

    'title' => 'Smart Industry Digital Library',
    'welcome-msg' => 'Welcome to the knowledge Base! Feel free to view :count articles in this place!',
    'new' => 'New',
    'popular' => 'Popular',
    'hot_author' => 'Author Rank',
    'datatype' => 'Type',
    'techtype' => 'Technology',
    'forum' => 'Forum',
    'download' => 'Download',
    'download-alliance' => 'Resources from alliance',
    'download-industry' => 'Resources from industries',
    'download-app' => 'Download APP',
    'greeting' => 'Hi :name!',
    'lang' => '繁體中文',
    'lang-href' => 'lang/tw',
    'admin' => 'Administrator',
    'upload' => 'Upload article',
    'myfavorite' => 'My favorite',
    'myuploaded' => 'My uploads',
    'help' => 'Help',
    'contactus' => 'Contact us',
    'account' => 'Account setting',
    'logout' => 'Logout',
    'footer-title' => '智慧製造產業創新人才培育計畫 Ministry of Education &copy; 2016',
    'footer-phone' => '連絡電話',
    'sponsor' => 'Sponsor',
    'address' => 'Address',
    'advanced_search' => 'Advanced',
    'search_holder' => 'Search the database...',
    'post_question' => 'Post an question',
    'post_help' => 'Your question will be shown in here after the reviewed by the administrator.',
    'post_title' => 'Title',
    'post_title_help' => 'Pleas fill in the title of your post.',
    'post_content' => 'Content',
    'post_btn' => 'Post',
    'question_title' => 'Question',
    'register_title' => 'Register',
    'register' => 'Register',
    'login' => 'Login',
    'login_help' => 'Already have an account? Sign in',
    'email' => 'Email',
    'email_holder' => 'Your email address.',
    'email_help' => 'It will be as your login account.',
    'password' => 'Password',
    'password_holder' => 'Passwords must be at least six characters and match the confirmation.',
    'confirmed_password' => 'Confirm your password.',
    'identity' => 'Job title',
    'student' => 'Student',
    'teacher' => 'Teacher',
    'engineer' => 'Engineer',
    'others' => 'Others',
    'myname' => 'Name',
    'name_holder' => 'Please fill in your name.',
    'name_help' => 'Please confirm your name.',
    'company' => 'Organization (University)',
    'company_holder' => 'Please fill in your organization.',
    'department' => 'Department',
    'department-holder' => 'Please fill in your department.',
    'id' => 'Employee (Student) ID',
    'id_holder' => 'Please fill in your ID.',
    'cellphone' => 'Phone',
    'cellphone_holder' => 'Please fill in your cellphone.',
    'privacy' => 'Privacy',
    'privacy_content' => 'My Privacy',
    'confirm' => 'Confirm',
    'register_help' => 'Please check the above information again.',
    'submit-btn' => 'Submit',
    'keep-alive' => 'Remember me',
    'forgot-password' => 'Forgot password?',
    'recommend' => 'Recommend',
    'warning404' => 'Oops! 404 Not Found!',
    'warning_info' => 'Sorry! We can not find the page! Please click',
    'home' => ' back to home page.',
    'modify' => 'Modify Profile',
    'profile' => 'Profile',
    'modify_pwd' => 'Change password',
    'origin_pwd' => 'Old Password',
    'origin_pwd_holder' => 'Please fill in your old password',
    'new_pwd' => 'New password',
    'author-info' => 'We can not find any paper',
    'search_results' => 'Results from ',
    'search_count' => ', total：',
    'keyword' => 'Keywords',
    'abstract' => 'Abstract',
    'link' => 'Link',
    'author' => 'Author',
    'country' => 'Country',
    'published_date' => 'Published Year',
    'from' => 'Origin',
    'unit' => 'Organization',
    'level' => 'Level',
    'comment_title' => 'Comment',
    'comment-content' => 'Post a comment',
    'favorite' => 'Favorite',
    'views' => 'Views',
 




];
